'use strict';
// ── PIXEL-GRID ACTORS ─────────────────────────────────────────
// Player and raider art as hand-placed pixel maps: one character = one pixel, '.' is clear,
// '_' erases (attack overlays use it to remove the resting weapon arm), every other
// character is looked up in the actor's palette. Frames are 44x60 and the figure is
// centred on x = 22 so flipX does not shift it. Layers paint in order: legs, body, head.
// grep: "paintGrid"  "SPRITE_ART"  "PLAYER_PAL"  "LEGS"

function paintGrid(layers, pal, w, h) {
  const c = document.createElement('canvas'); c.width = w || 44; c.height = h || 60;
  const ctx = c.getContext('2d');
  for (const L of layers) {
    if (!L) continue;
    const [ox, oy] = L.at;
    L.rows.forEach((row, y) => {
      for (let x = 0; x < row.length; x++) {
        const ch = row[x];
        if (ch === '.') continue;
        const px = ox + (L.flip ? row.length - 1 - x : x), py = oy + y;
        if (ch === '_') { ctx.clearRect(px, py, 1, 1); continue; }
        const col = pal[ch];
        if (col === undefined) throw new Error('paintGrid: no colour for "' + ch + '"');
        ctx.fillStyle = col; ctx.fillRect(px, py, 1, 1);
      }
    });
  }
  return c;
}

// Shared leg band. P/p trousers, F/f boots, centred on x = 22, top y = 34 (4 hip rows).
const LEGS = {
  front: [
    '..PPPPPPPPPPPp..',
    '..PPPPPPPPPPPp..',
    '..PPPPPPPPPPPp..',
    '..PPPPPPPPPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '.FFFFFf..FFFFFf.',
    '.FFFFFf..FFFFFf.',
    '.FFFFFf..FFFFFf.',
    'FFFFFFf..FFFFFFf',
    'FFFFFFf..FFFFFFf',
    'ffffff....ffffff',
  ],
  front_step: [
    '..PPPPPPPPPPPp..',
    '..PPPPPPPPPPPp..',
    '..PPPPPPPPPPPp..',
    '..PPPPPPPPPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '..PPPPp..PPPPp..',
    '.FFFFFf..PPPPp..',
    '.FFFFFf..PPPPp..',
    '.FFFFFf..PPPPp..',
    'FFFFFFf..FFFFFf.',
    'FFFFFFf..FFFFFf.',
    'ffffff...FFFFFf.',
    '.........FFFFFFf',
    '.........FFFFFFf',
    '..........ffffff',
  ],
  side: [
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppFFFFFf.....',
    '.....ppppFFFFFf.....',
    '.....ffffFFFFFf.....',
    '.....ffffFFFFFFFf...',
    '.....ffffFFFFFFFFf..',
    '.....ffffffffffff...',
  ],
  side_step: [
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '.....ppppPPPPPp.....',
    '....pppp.pPPPPPp....',
    '....pppp..PPPPPp....',
    '...pppp...pPPPPPp...',
    '...pppp....PPPPPp...',
    '...pppp....pPPPPPp..',
    '..pppp......PPPPPp..',
    '..pppp......pPPPPPp.',
    '..pppp.......PPPPPp.',
    '.pppp........PPPPPp.',
    '.pppp........PPPPPp.',
    '.pppp........PPPPPp.',
    '.pppp........PPPPPp.',
    '.ffff........FFFFFf.',
    '.ffff........FFFFFf.',
    'fffff........FFFFFFf',
    'fffff........FFFFFFF',
    'ffff.........FFFFFFF',
    '.............fffffff',
  ],
};

// The heavy raider's armour needs thicker legs than the shared set.
const HEAVY_LEGS = {
  front: [
    '..PPPPPPPPPPPPPPPp..',
    '..PPPPPPPPPPPPPPPp..',
    '..PPPPPPPPPPPPPPPp..',
    '..PPPPPPPPPPPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '.FFFFFFFf..FFFFFFFf.',
    '.FFFFFFFf..FFFFFFFf.',
    '.FFFFFFFf..FFFFFFFf.',
    'FFFFFFFFf..FFFFFFFFf',
    'FFFFFFFFf..FFFFFFFFf',
    'ffffffff....ffffffff',
  ],
  front_step: [
    '..PPPPPPPPPPPPPPPp..',
    '..PPPPPPPPPPPPPPPp..',
    '..PPPPPPPPPPPPPPPp..',
    '..PPPPPPPPPPPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '..PPPPPPp..PPPPPPp..',
    '.FFFFFFFf..PPPPPPp..',
    '.FFFFFFFf..PPPPPPp..',
    '.FFFFFFFf..PPPPPPp..',
    'FFFFFFFFf..FFFFFFFf.',
    'FFFFFFFFf..FFFFFFFf.',
    'ffffffff...FFFFFFFf.',
    '...........FFFFFFFFf',
    '...........FFFFFFFFf',
    '............ffffffff',
  ],
  side: [
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppFFFFFFf.....',
    '.....fffffFFFFFFf.....',
    '.....fffffFFFFFFFFf...',
    '.....fffffffffffff....',
  ],
  side_step: [
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '.....pppppPPPPPPp.....',
    '....ppppp.pPPPPPPp....',
    '....ppppp..PPPPPPp....',
    '...ppppp...pPPPPPPp...',
    '...ppppp....PPPPPPp...',
    '...ppppp....pPPPPPPp..',
    '..ppppp......PPPPPPp..',
    '..ppppp......pPPPPPPp.',
    '..ppppp.......PPPPPPp.',
    '.ppppp........PPPPPPp.',
    '.ppppp........PPPPPPp.',
    '.ppppp........PPPPPPp.',
    '.ppppp........PPPPPPp.',
    '.ppppp........PPPPPPp.',
    '.ppppp........PPPPPPp.',
    '.fffff........FFFFFFf.',
    'ffffff........FFFFFFFf',
    'ffffff........FFFFFFFF',
    'fffff.........FFFFFFFF',
    '..............ffffffff',
  ],
};

const PLAYER_PAL = {
  knight: {
    A: '#5d7fa0', a: '#3b5670', Q: '#a9c6e0', o: '#1c2733',
    S: '#f2c39b', s: '#d59a72', E: '#1a1420', W: '#ffffff', m: '#b0605a',
    R: '#d63c3c', r: '#8f2222', B: '#2c52b4', b: '#1b3680', G: '#ecbc34', g: '#a87818',
    L: '#5a3a20', M: '#e4e9ef', N: '#9aa6b4', D: '#6e4a24',
    P: '#4d6b88', p: '#33495f', F: '#2a3a4c', f: '#161f2a',
  },
  gunslinger: {
    H: '#6b4423', h: '#45290f', I: '#8e6236', K: '#24160a',
    C: '#c98a3a', c: '#8a5a22', Y: '#e6ae60', W: '#ebe4d4', w: '#b8ae9c',
    R: '#b83030', r: '#7a1e1e', O: '#4a3020', X: '#2e1c10',
    S: '#eab48c', s: '#c98d66', E: '#1a1420',
    L: '#3a2412', G: '#d8b040', M: '#a4acb6', N: '#4a5058', D: '#6e4a24',
    P: '#3d5a8a', p: '#2a3f63', F: '#5a3a1e', f: '#36220e',
  },
  architect: {
    Y: '#f0c020', y: '#b08410', Z: '#fff4a0',
    A: '#3a9a55', a: '#1f6635', Q: '#6cc884', o: '#123d20', W: '#dfe6df',
    H: '#6a4428', h: '#43280f', S: '#eab48c', s: '#c98d66', E: '#1a1420',
    L: '#4a3018', T: '#a07040', t: '#6e4a24', G: '#d8b040',
    M: '#c4ccd4', N: '#6a727c',
    P: '#2e3a5c', p: '#1e2640', F: '#4a3420', f: '#2a1c10',
  },
  charmer: {
    H: '#c0612c', h: '#84391a', J: '#e08a4a',
    A: '#8a4fb8', a: '#5c2e80', Q: '#b07ad8', o: '#2a1630',
    K: '#d988bb', k: '#995577', U: '#f0b0d8',
    S: '#f0c4a0', s: '#cf9a76', E: '#1a1420', m: '#b85a6a',
    L: '#4a2a3a', G: '#d8b040', R: '#ff5070', r: '#b02848', Y: '#ffd040', V: '#3a8a3a', v: '#24602a',
    P: '#4a3058', p: '#2e1c38', F: '#6a3a50', f: '#3e2030',
  },
  ranger: {
    A: '#4f6e2e', a: '#304418', Q: '#7a9a4a', o: '#1a2410',
    T: '#8a5a30', t: '#5a3818', H: '#6a4020', h: '#43260f',
    S: '#eab48c', s: '#c98d66', E: '#1a1420',
    D: '#a87438', d: '#6a4418', W: '#e8e0c8', M: '#c8d0d8', L: '#3a2410', G: '#c0a040', R: '#c84040',
    P: '#4a4030', p: '#2e281c', F: '#3e2a18', f: '#24180c',
  },
  raider_brawler: {
    R: '#b02e22', r: '#6a160e', V: '#5a3020', v: '#3a1c10', S: '#c98a5c', s: '#9a6440',
    E: '#1a1010', o: '#1a0e08', M: '#b8bec6', D: '#7a5228', d: '#4a3014',
    L: '#2a1a10', G: '#9a8a50', P: '#5a4a38', p: '#3a3024', F: '#2a2018', f: '#160f0a',
  },
  raider_shooter: {
    H: '#7a6a50', h: '#4e4230', J: '#9a8a6a', C: '#5e6040', c: '#3c3e28', Y: '#7e8058',
    K: '#c08030', B: '#5fd4e8', b: '#2a7080', X: '#8a3a2a', x: '#5a2218',
    S: '#c98a5c', s: '#9a6440', L: '#2a1a10', M: '#7a828c', N: '#3a4048', D: '#6e4a24',
    P: '#4a4438', p: '#2e2a22', F: '#2a2018', f: '#160f0a',
  },
  raider_heavy: {
    A: '#6a7a8a', a: '#45525e', Q: '#98a8b8', o: '#1a2026', r: '#9a5a30', E: '#ff4a2a',
    L: '#2a1a10', G: '#9a8a50', D: '#6e4a24', d: '#4a3014', M: '#5a626c', N: '#353b42',
    P: '#3e4248', p: '#272a2e', F: '#2a2a2a', f: '#141414',
  },
};

// Each part: { at: [x, y], rows }. Frames list which parts they stack.
const SPRITE_ART = {
  knight: {
    front: {
      head: { at: [15, 3], rows: [
        '......RRr.....',
        '.....RRRRr....',
        '.....RRRRr....',
        '....rRRRr.....',
        '...aAQQQAAa...',
        '..aAQQAAAAAa..',
        '.aAQAAAAAAAAa.',
        '.aAAAAAAAAAAa.',
        '.aAooooooooAa.',
        '.aAosEssEsoAa.',
        '.aAoSESSESoAa.',
        '.aAoSSssSSoAa.',
        '.aAAosSSsoAAa.',
        '.aAAAossoAAAa.',
        '..aAAAAAAAAa..',
        '...aaaaaaaa...',
      ] },
      body: { at: [10, 19], rows: [
        '........aAAAAAAa........',
        '..aQQAAa.aAAAAa.aQQAAa..',
        '.aQQAAAAaBBBBBBaQQAAAAa.',
        '.aQAAAAAaBBBBBBaQAAAAAa.',
        '.aAAAAAaABBGGBBAaAAAAAa.',
        '..aaaaaoABGGGGBAoaaaaa..',
        '..aAAaoAABBGGBBAAoaAAa..',
        '..aAAaoAABBBBBBAAoaAAa..',
        '..aAAaoAAABBBBAAAoaAAa..',
        '..aAAaoaAABBBBAAaoaAAa..',
        '..aAAaoLLLLGGLLLLoaAAa..',
        '..aAAaoaAABBBBAAaoaAAa..',
        '..aAAa.aAABBBBAAa.aAAa..',
        '..aQQa.aAABBBBAAa.aQQa..',
        '..aAAa.aaaBBBBaaa.aAAa..',
        '...aa...aaBBBBaa...aa...',
        '.........aBBBBa.........',
        '..........bBBb..........',
        '...........bb...........',
      ] },
      over: { at: [8, 25], rows: [
        'GGGGGGGGg',
        'GBBBBBBBg',
        'GBQBBBBbg',
        'GBBBGBBbg',
        'GBBGGGBbg',
        'GBBBGBBbg',
        'GBBBBBBbg',
        '.GBBBBbg.',
        '.GBBBBbg.',
        '..GBBbg..',
        '..GBbbg..',
        '...Gg....',
      ] },
      weapon: { at: [26, 8], rows: [
        '....M....', '...MN....', '...MN....', '...MN....', '...MN....', '...MN....',
        '...MN....', '...MN....', '...MN....', '...MN....', '...MN....', '...MN....',
        '...MN....', '...MN....', '...MN....', '...MN....', '...MN....', '...MN....',
        '...MN....', '...MN....', '...MN....', '...MN....',
        '.GGGGGGg.',
        '...DD....',
        '..aQQa...',
        '..aAAa...',
        '...DD....',
        '...Gg....',
      ] },
      atk: { at: [26, 29], rows: [
        '..................',
        '..aQQaGMMMMMMMMMMM',
        '..aAAaGNNNNNNNNNNN',
        '......g...........',
      ] },
    },
    back: {
      head: { at: [15, 3], rows: [
        '......RRr.....',
        '.....RRRRr....',
        '.....RRRRr....',
        '....rRRRr.....',
        '...aAQQQAAa...',
        '..aAQQAAAAAa..',
        '.aAQAAAAAAAAa.',
        '.aAAAAAAAAAAa.',
        '.aAAAAAAAAAAa.',
        '.aAAAAAAAAAAa.',
        '.aAAAAAAAAAAa.',
        '.aaAAAAAAAAaa.',
        '.aaaAAAAAAaaa.',
        '.oaaaaaaaaaao.',
        '..aAAAAAAAAa..',
        '...aaaaaaaa...',
      ] },
      body: { at: [10, 19], rows: [
        '........aAAAAAAa........',
        '..aQQAAa.aAAAAa.aQQAAa..',
        '.aQQAAAAaAAAAAAaQQAAAAa.',
        '.aQAAAAAaAQAAAAaQAAAAAa.',
        '.aAAAAAaAAAAAAAAaAAAAAa.',
        '..aaaaaoAAAAAAAAoaaaaa..',
        '..aAAaoAAAAAAAAAAoaAAa..',
        '..aAAaoAAAaAAaAAAoaAAa..',
        '..aAAaoAAAaAAaAAAoaAAa..',
        '..aAAaoaAAAAAAAAaoaAAa..',
        '..aAAaoLLLLLLLLLLoaAAa..',
        '..aAAaoaAAAAAAAAaoaAAa..',
        '..aAAa.aAAAaaAAAa.aAAa..',
        '..aQQa.aAAAaaAAAa.aQQa..',
        '..aAAa.aaaaaaaaaa.aAAa..',
        '...aa...aa....aa...aa...',
      ] },
      behind: { at: [8, 25], rows: [
        'GGGGGGGGg',
        'GbbbbbbbG',
        'GbLbbbLbg',
        'GbLbbbLbg',
        'GbbbbbbbG',
        'GbbbbbbbG',
        'GbbbbbbbG',
        '.GbbbbbG.',
        '.GbbbbbG.',
        '..GbbbG..',
        '..GbbbG..',
        '...Gg....',
      ] },
      weapon: { at: [26, 8], rows: [
        '....M....', '...MN....', '...MN....', '...MN....', '...MN....', '...MN....',
        '...MN....', '...MN....', '...MN....', '...MN....', '...MN....', '...MN....',
        '...MN....', '...MN....', '...MN....', '...MN....', '...MN....', '...MN....',
        '...MN....', '...MN....', '...MN....', '...MN....',
        '.GGGGGGg.',
      ] },
      atk: { at: [26, 4], rows: [
        '............MN....',
        '...........MN.....',
        '..........MN......',
        '.........MN.......',
        '........MN........',
        '.......MN.........',
        '......MN..........',
        '.....MN...........',
        '....MN............',
        '...MN.............',
        '..GMg.............',
        '.G.Dg.............',
      ] },
    },
    side: {
      head: { at: [15, 3], rows: [
        '...RRr........',
        '..RRRRr.......',
        '.rRRRr........',
        'rRr.aAQQAAa...',
        'r..aAQQAAAAAa.',
        '..aAQAAAAAAAAa',
        '..aAAAAAAAAAAa',
        '..aAAAAAAoooo.',
        '..aAAAAAAosEs.',
        '..aAAAAAAoSES.',
        '..aAAAAAAoSSs.',
        '..aAAAAAAAosS.',
        '..aAAAAAAAAAa.',
        '...aAAAAAAAa..',
        '...aaaaaaaa...',
      ] },
      body: { at: [10, 19], rows: [
        '.........aAAAAa.........',
        '.......aAAAAAAAAa.......',
        '......aAAAQQAAAAAa......',
        '......aAAQQQQAAAAa......',
        '......aAAQAAAAAABa......',
        '......aAaaaaaaAABa......',
        '......aAoaAAAaoABa......',
        '......aAoaAAAaoABa......',
        '......aAoaAAAaoABa......',
        '......aAoaAAAaoABa......',
        '......LLoaAAAaoLLL......',
        '......aAoaAAAaoABa......',
        '......aAoaQQQaoABa......',
        '......aAoaAAAaoaBa......',
        '.......aa.aaa..aBb......',
        '...............bb.......',
      ] },
      behind: { at: [27, 25], rows: [
        'GGGg',
        'BBBg',
        'BBBg',
        'GBBg',
        'GBBg',
        'BBBg',
        'BBbg',
        'Bbg.',
        'bg..',
      ] },
      weapon: { at: [19, 13], rows: [
        '.................M..',
        '................MN..',
        '...............MN...',
        '..............MN....',
        '.............MN.....',
        '............MN......',
        '...........MN.......',
        '..........MN........',
        '.........MN.........',
        '........MN..........',
        '.......MN...........',
        '......MN............',
        '...G.MN.............',
        '....GN..............',
        '...DGg..............',
        '..DD.g..............',
        '.aQQa...............',
        '.aAAa...............',
        '.D..................',
      ] },
      atk: { at: [16, 25], rows: [
        'aAAAAAAAABa.................',
        'aAAAAAAAABa.................',
        'aAAAQQQAaaaaaaG.............',
        'aAAAAAAAAAAaQQGMMMMMMMMMMMMM',
        'aAAAAAAAAAAaAAGNNNNNNNNNNNNN',
        'LLLLLLLLLLL...g.............',
        'aAAAAAAAABa.................',
        'aAAAAAAAABa.................',
        'aAAAAAAAaBa.................',
      ] },
    },
    fside: { base: 'front',
      head: { at: [15, 3], rows: [
        '......RRr.....',
        '.....RRRRr....',
        '....rRRRRr....',
        '...rRRRr......',
        '...aAQQQAAa...',
        '..aAQQAAAAAa..',
        '.aAQAAAAAAAAa.',
        '.aAAAAAAAAAAa.',
        '.aAAAoooooooa.',
        '.aAAAosEssEsa.',
        '.aAAAoSESSESa.',
        '.aAAAoSSsSSsa.',
        '.aAAAAosSSsoa.',
        '.aAAAAAossoAa.',
        '..aAAAAAAAAa..',
        '...aaaaaaaa...',
      ] },
    },
    bside: { base: 'back' },
  },
  gunslinger: {
    front: {
      head: { at: [13, 5], rows: [
        '......hHHHHh......',
        '.....hHHIHHHh.....',
        '.....hHIHHHHh.....',
        '.....hKKKKKKh.....',
        'hh..hHHHHHHHHh..hh',
        '.hhhHHIHHHHHHHhhh.',
        '...hhhhhhhhhhhh...',
        '....ssssssssss....',
        '....SsEsSSsEsS....',
        '....SSESSSSESS....',
        '....SSSSssSSSS....',
        '....sSSSSSSSSs....',
        '....sSSSssSSSs....',
        '.....ssssssss.....',
      ] },
      body: { at: [10, 19], rows: [
        '........RRRRRRRR........',
        '...cCCYCrRRRRRRrCYCCc...',
        '..cCCYCCCrRRRRrCCCYCCc..',
        '..cCYCCCCWrRRrWCCCCYCc..',
        '..cCCCcCCWWrrWWCCcCCCc..',
        '..cCCCccCWWWWWWCccCCCc..',
        '..cCCCcCCWWWWWWCCcCCCc..',
        '..cCCCcCCWWwWWWCCcCCCc..',
        '..cCCCcCCWWWWWWCCcCCCc..',
        '..cCCCcCCWWWWWWCCcCCCc..',
        '..cCCCcLLLLGGLLLLcCCCc..',
        '..cCCCcCCPPPPPPCCcCCCc..',
        '..cCCCcCCPPPPPPCCcCCCc..',
        '..sSSs.CCPPPPPPCC.sSSs..',
        '..sSSs.CCPPPPPPCC.sSSs..',
        '.......CCCPPPPCCC.......',
        '.......cCCPppPCCc.......',
        '.......cCCC..CCCc.......',
        '.......cCCC..CCCc.......',
        '.......cCCc..cCCc.......',
        '.......cCCc..cCCc.......',
        '.......ccc....ccc.......',
      ] },
      weapon: { at: [28, 33], rows: [
        '.DDN',
        '.NMMN',
        '.NMMN',
        '..MN.',
        '..MN.',
        '..N..',
      ].map(r => r.padEnd(5, '.')) },
      atk: { at: [26, 30], rows: [
        '......NNMMMMMMMN..',
        '..sSSsNMMNNNNNN...',
        '..sSSsDD..........',
        '.......D..........',
      ] },
    },
    back: {
      head: { at: [13, 5], rows: [
        '......hHHHHh......',
        '.....hHHIHHHh.....',
        '.....hHIHHHHh.....',
        '.....hKKKKKKh.....',
        'hh..hHHHHHHHHh..hh',
        '.hhhHHIHHHHHHHhhh.',
        '...hhhhhhhhhhhh...',
        '....OOOOOOOOOO....',
        '....OOOOOOOOOO....',
        '....OOOOOOOOOO....',
        '....XOOOOOOOOX....',
        '....sXOOOOOOXs....',
        '....sSSSSSSSSs....',
        '.....ssssssss.....',
      ] },
      body: { at: [10, 19], rows: [
        '........RRRRRRRR........',
        '...cCCYCCCCCCCCCCYCCc...',
        '..cCCYCCCCCCCCCCCCYCCc..',
        '..cCYCCCCCCCCCCCCCCYCc..',
        '..cCCCcCCCCCCCCCCcCCCc..',
        '..cCCCcCCCCCCCCCCcCCCc..',
        '..cCCCcCCCCCCCCCCcCCCc..',
        '..cCCCcCCCCCCCCCCcCCCc..',
        '..cCCCcCCCCCCCCCCcCCCc..',
        '..cCCCcCCCCCCCCCCcCCCc..',
        '..cCCCcLLLLLLLLLLcCCCc..',
        '..cCCCcCCCCcCCCCCcCCCc..',
        '..cCCCcCCCCcCCCCCcCCCc..',
        '..sSSs.CCCCcCCCCC.sSSs..',
        '..sSSs.CCCCcCCCCC.sSSs..',
        '.......CCCCcCCCCC.......',
        '.......cCCCcCCCCc.......',
        '.......cCCCccCCCc.......',
        '.......cCCC..CCCc.......',
        '.......cCCc..cCCc.......',
        '.......cCCc..cCCc.......',
        '.......ccc....ccc.......',
      ] },
    },
    side: {
      head: { at: [13, 5], rows: [
        '.......hHHHHh.....',
        '......hHIHHHHh....',
        '......hHHHHHHh....',
        '......hKKKKKKh....',
        '..hhhhHHHHHHHHhhh.',
        '...hhhhhhhhhhhhhhh',
        '......OOOsssssss..',
        '......OOOSSSSEsS..',
        '......OOOSSSSESS..',
        '......OOOSSSSSSSs.',
        '......XOOSSSSSSs..',
        '.......XsSSSSSs...',
        '........ssssss....',
      ] },
      body: { at: [10, 19], rows: [
        '.........RRRRRr.........',
        '.......cCCCCCCWRc.......',
        '......cCCYYCCCCWWc......',
        '......cCYYYYCCCWWc......',
        '......cCYCCCCCCWWc......',
        '......cCCccccccWWc......',
        '......cCcCCCCcCWWc......',
        '......cCcCCCCcCWWc......',
        '......cCcCCCCcCWWc......',
        '......cCcCCCCcCWWc......',
        '......cLcCCCCcLLLc......',
        '......cCcCCCCcCPPc......',
        '......cCcsSSScCPPc......',
        '......cCcsSSScCPPc......',
        '......cCCccccCCCCc......',
        '......cCCCCCCCCCCc......',
        '......cCCCCCCCCCCc......',
        '.....cCCCCCCCCCCCc......',
        '.....cCCCCCCCCCCc.......',
        '.....ccCCCCCCCCc........',
        '......cccccccccc........',
      ] },
      weapon: { at: [20, 33], rows: [
        '..DDN',
        '.NMMN',
        '.NMMN',
        '..MN.',
        '..MN.',
        '..N..',
      ] },
      atk: { at: [16, 25], rows: [
        'cCCCCCCCCWWc................',
        'cCYYYYYYYYYYYYYYYYYc........',
        'cCCCCCCCCCCCCCCCCCCcsSSsMMMM',
        'cCccccccccccccccccccsSSsDNN.',
        'cLLLLLLLLLLc........DD......',
        'cCCCCCCCCPPc................',
        'cCCCCCCCCPPc................',
        'cCCCCCCCCPPc................',
      ] },
    },
    fside: { base: 'front',
      head: { at: [13, 5], rows: [
        '......hHHHHh......',
        '.....hHHIHHHh.....',
        '.....hHIHHHHh.....',
        '.....hKKKKKKh.....',
        'hh..hHHHHHHHHh..hh',
        '.hhhHHIHHHHHHHhhh.',
        '...hhhhhhhhhhhh...',
        '....OOssssssss....',
        '....OOSSsEsSsE....',
        '....OOSSSESSSE....',
        '....OOSSSSSSSSs...',
        '....XOSSSSSSSs....',
        '....XsSSSSSSSs....',
        '.....ssssssss.....',
      ] },
    },
    bside: { base: 'back' },
  },
  architect: {
    front: {
      head: { at: [14, 5], rows: [
        '.....yYYYYy.....',
        '...yYZZYYYYYy...',
        '..yYZYYYYYYYYy..',
        '..yYYYYYYYYYYy..',
        '.yyyyyyyyyyyyyy.',
        '...hhhhhhhhhh...',
        '...hsEssssEsh...',
        '...SSESSSSESS...',
        '...SSSSssSSSS...',
        '...HSSSSSSSSH...',
        '...HHHHSSHHHH...',
        '...HHHHHHHHHH...',
        '....HHHHHHHH....',
        '.....hhhhhh.....',
      ] },
      body: { at: [10, 19], rows: [
        '.........aAAAAa.........',
        '..aQQAAAaAAAAAAaQQAAAa..',
        '.aQQAAAAaAAAAAAaQQAAAAa.',
        '.aQAAAAAaAAAoAAaQAAAAAa.',
        '.aAAAAAaWWWWWWWWaAAAAAa.',
        '..aAAAaaAAAoAAAAaaAAAa..',
        '..aAAAaoAAAoAAAAoaAAAa..',
        '..aAAAaoAAAoAAAAoaAAAa..',
        '..aAAAaoWWWWWWWWoaAAAa..',
        '..aAAAaoAAAoAAAAoaAAAa..',
        '..aAAAaoTTLGGLTToaAAAa..',
        '..aAAAaoTtPPPPtToaAAAa..',
        '..sSSSs.TtPPPPtT.sSSSs..',
        '..sSSSs..PPPPPP..sSSSs..',
        '...sss...PPPPPP...sss...',
      ] },
      weapon: { at: [28, 33], rows: [
        '..MN.',
        '..MN.',
        '..MN.',
        '..MN.',
        '.MNNM',
        'MN..M',
        'MN..N',
      ] },
      atk: { at: [27, 30], rows: [
        '..............M.M',
        'sSSSsMMMMMMMMMMNM',
        'sSSSsNNNNNNNNNNNN',
        '..............N.N',
      ] },
    },
    back: {
      head: { at: [14, 5], rows: [
        '.....yYYYYy.....',
        '...yYZZYYYYYy...',
        '..yYZYYYYYYYYy..',
        '..yYYYYYYYYYYy..',
        '.yyyyyyyyyyyyyy.',
        '...hhhhhhhhhh...',
        '...hHHHHHHHHh...',
        '...hHHHHHHHHh...',
        '...hHHHHHHHHh...',
        '...shHHHHHHhs...',
        '...sShhhhhhSs...',
        '...sSSSSSSSSs...',
        '....ssssssss....',
      ] },
      body: { at: [10, 19], rows: [
        '.........aAAAAa.........',
        '..aQQAAAaAAAAAAaQQAAAa..',
        '.aQQAAAAaAAAAAAaQQAAAAa.',
        '.aQAAAAAaAAAAAAaQAAAAAa.',
        '.aAAAAAaWWWWWWWWaAAAAAa.',
        '..aAAAaaAAAAAAAAaaAAAa..',
        '..aAAAaoAAAAAAAAoaAAAa..',
        '..aAAAaoAAAAAAAAoaAAAa..',
        '..aAAAaoWWWWWWWWoaAAAa..',
        '..aAAAaoAAAAAAAAoaAAAa..',
        '..aAAAaoTTLLLLTToaAAAa..',
        '..aAAAaoTtPPPPtToaAAAa..',
        '..sSSSs.TtPPPPtT.sSSSs..',
        '..sSSSs..PPPPPP..sSSSs..',
        '...sss...PPPPPP...sss...',
      ] },
    },
    side: {
      head: { at: [14, 5], rows: [
        '......yYYYYy....',
        '....yYZZYYYYy...',
        '...yYZYYYYYYYy..',
        '...yYYYYYYYYYy..',
        '..yyyyyyyyyyyyyy',
        '....hhhhhhhhh...',
        '....hhhhssEss...',
        '....hhhhSSSES...',
        '....hhhSSSSSSs..',
        '....hhHSSSSSS...',
        '.....hHHHHHHH...',
        '.....hHHHHHHH...',
        '......HHHHHH....',
        '.......hhhh.....',
      ] },
      body: { at: [10, 19], rows: [
        '..........aAAAa.........',
        '........aAAAAAAAa.......',
        '.......aAAQQAAAAAa......',
        '.......aAQQQQAAAAa......',
        '.......aAQAAAAAAWa......',
        '.......aAaaaaaaAWa......',
        '.......aAoaAAAaoWa......',
        '.......aAoaAAAaoAa......',
        '.......aAoaAAAaoAa......',
        '.......aWoWWWWWoWa......',
        '.......TToaAAAaoLT......',
        '.......TtoaAAAaoPt......',
        '.......TtosSSSsoPt......',
        '........PPsSSSsPPP......',
        '........PPPsssPPPP......',
      ] },
      weapon: { at: [20, 33], rows: [
        '..MN.',
        '..MN.',
        '..MN.',
        '..MN.',
        '.MNNM',
        'MN..M',
        'MN..N',
      ] },
      atk: { at: [17, 24], rows: [
        'aAAAAAAAAWa................',
        'aAAAAAAAAWa................',
        'aAQQQQQQQQQQQQQQQQa........',
        'aAAAAAAAAAAAAAAAAAasSSsM.M.',
        'aWaaaaaaaaaaaaaaaaasSSsMMMM',
        'TTLLLLLLLLLT.........NNNNNN',
        'TtAAAAAAAPPt...........N.N.',
        'TtAAAAAAAPPt...............',
      ] },
    },
    fside: { base: 'front',
      head: { at: [14, 5], rows: [
        '.....yYYYYy.....',
        '...yYZZYYYYYy...',
        '..yYZYYYYYYYYy..',
        '..yYYYYYYYYYYy..',
        '.yyyyyyyyyyyyyy.',
        '...hhhhhhhhhh...',
        '...hhhssEssssE..',
        '...hhSSSESSSSE..',
        '...hhSSSSSSsSSs.',
        '...hHSSSSSSSSS..',
        '...hHHHHSSHHHH..',
        '....HHHHHHHHHH..',
        '.....HHHHHHHH...',
        '......hhhhhh....',
      ] },
    },
    bside: { base: 'back' },
  },
  charmer: {
    front: {
      head: { at: [14, 4], rows: [
        '.....hHHHHh.....',
        '...hHHJJHHHHh...',
        '..hHJJHHHHHHHh..',
        '.hHJHHHHHHHHHHh.',
        '.hHHHHHHHHHHRYh.',
        '.hHHhhhhhhhhRrh.',
        '.hHhSSSSSSSShHh.',
        '.hHhsEssssEshHh.',
        '.hHhSESSSSEShHh.',
        '.hHhSSSssSSShHh.',
        '.hHHsSSSSSSsHHh.',
        '.hHHhsSmmSshHHh.',
        '.hHHHhsssshHHHh.',
        '.hHHh......hHHh.',
        '.hHHh......hHHh.',
        '..hh........hh..',
      ] },
      body: { at: [10, 19], rows: [
        '..........SSSS..........',
        '....aQAaAAAAAAAAaAQa....',
        '...aQQAaAAQAAAAAaAQQa...',
        '...aQAAaAAAAAAAAaAQAa...',
        '...aAAaoAAAGGAAAoaAAa...',
        '...aAAaoAAAAAAAAoaAAa...',
        '...aAAaoaAAAAAAaoaAAa...',
        '...aAAa.oaAAAAao.aAAa...',
        '...aAAa.oLLGGLLo.aAAa...',
        '...aAAa.KKKKKKKK.aAAa...',
        '...sSSsKKUKKKKKKksSSs...',
        '...sSSsKUKKKKKKKksSSs...',
        '......KUKKKKKKKKKk......',
        '.....KUKKKKKKKKKKKk.....',
        '.....kKkKKkKKkKKkKk.....',
        '......kk.kk..kk.kk......',
      ] },
      weapon: { at: [26, 24], rows: [
        '.R.Rr.',
        'RYRRYR',
        'rRrRRr',
        '.VRYV.',
        '..VV..',
        '..vV..',
      ] },
      atk: { at: [27, 20], rows: [
        'Q................',
        'QQQQQQQQQsSs.R.Rr',
        'aaaaaaaaasSsRYRRY',
        '___.......V.rRrRr',
        '___........V.VV..',
        '___..............',
        '___..............',
        '___..............',
        '___..............',
        '___..............',
        '___..............',
        '___..............',
      ] },
    },
    back: {
      head: { at: [14, 4], rows: [
        '.....hHHHHh.....',
        '...hHHJJHHHHh...',
        '..hHJJHHHHHHHh..',
        '.hHJHHHHHHHHHHh.',
        '.hHHHHHHHHHHRYh.',
        '.hHHHHHHHHHHRrh.',
        '.hHHHHJHHHHHHHh.',
        '.hHHHJHHHHHHHHh.',
        '.hHHHHHHHHHHHHh.',
        '.hHHHHHHHHHHHHh.',
        '.hHHHHHHHHHHHHh.',
        '.hHHHHHHHHHHHHh.',
        '.hHHHHHHHHHHHHh.',
        '.hHHHHHHHHHHHHh.',
        '..hHHHHHHHHHHh..',
        '...hHHHHHHHHh...',
        '....hHHHHHHh....',
        '.....hhhhhh.....',
      ] },
      body: { at: [10, 19], rows: [
        '..........SSSS..........',
        '....aQAaAAAAAAAAaAQa....',
        '...aQQAaAAAAAAAAaAQQa...',
        '...aQAAaAAAAAAAAaAQAa...',
        '...aAAaoAAAAAAAAoaAAa...',
        '...aAAaoAAAAAAAAoaAAa...',
        '...aAAaoaAAAAAAaoaAAa...',
        '...aAAa.oaAAAAao.aAAa...',
        '...aAAa.oLLLLLLo.aAAa...',
        '...aAAa.KKKKKKKK.aAAa...',
        '...sSSsKKUKKKKKKksSSs...',
        '...sSSsKUKKKKKKKksSSs...',
        '......KUKKKKKKKKKk......',
        '.....KUKKKKKKKKKKKk.....',
        '.....kKkKKkKKkKKkKk.....',
        '......kk.kk..kk.kk......',
      ] },
      weapon: { at: [26, 24], rows: [
        '.R.Rr.',
        'RYRRYR',
        'rRrRRr',
        '.VRYV.',
        '..VV..',
        '..vV..',
      ] },
      atk: { at: [27, 18], rows: [
        '..........R.Rr',
        '.........RYRRY',
        '........sSrRrR',
        '.......sSs.V..',
        '......sSs.....',
        '.....aQa......',
        '....aQa.......',
        '...aQa........',
      ] },
    },
    side: {
      head: { at: [14, 4], rows: [
        '....hHHHHh......',
        '..hHHJJHHHHh....',
        '.hHJJHHHHHHHh...',
        '.hHJHHHHHHHHHh..',
        'hHHHHHHHHRYHHh..',
        'hHHHHHHHHRrhhSh.',
        'hHHHHHHHHhSSSSh.',
        'hHHHHHHHhSSsEs..',
        'hHHHHHHHhSSSES..',
        'hHHHHHHHhSSSSSs.',
        'hHHHHHHHHsSSSs..',
        'hHHHHHHHHhsSmS..',
        'hHHHHHHHHhhss...',
        'hHHHHHHHHh......',
        '.hHHHHHHh.......',
        '.hHHHHHHh.......',
        '..hHHHHh........',
        '...hhhh.........',
      ] },
      body: { at: [10, 19], rows: [
        '...........SSS..........',
        '........aAAAAAAa........',
        '.......aAAQQAAAAa.......',
        '.......aAQQQQAAAa.......',
        '.......aAQAAAAAGa.......',
        '.......aAaaaaaAAa.......',
        '.......aAoaAAaoAa.......',
        '........aoaAAao.a.......',
        '........oLaAAaLLo.......',
        '........KKaAAaKKK.......',
        '.......KKKsSSsKKKk......',
        '......KUKKsSSsKKKKk.....',
        '......KUKKKKKKKKKKk.....',
        '.....KUKKKKKKKKKKKKk....',
        '.....kKkKKkKKkKKkKk.....',
        '......kk.kk..kk.kk......',
      ] },
      weapon: { at: [21, 24], rows: [
        '.R.Rr.',
        'RYRRYR',
        'rRrRRr',
        '.VRYV.',
        '..VV..',
        '..vV..',
      ] },
      atk: { at: [17, 24], rows: [
        'aAAAAAAa.............',
        'aAQQQQQQQQQQsSsR.Rr..',
        'aaaaaaaaaaaasSsRYRRYR',
        '.oAAAAAAo...V.rRrRr..',
        '.oLLLLLLo....V.VV....',
        '.KKAAAAKKK...........',
        'KKKAAAAKKKk..........',
      ] },
    },
    fside: { base: 'front',
      head: { at: [14, 4], rows: [
        '.....hHHHHh.....',
        '...hHHJJHHHHh...',
        '..hHJJHHHHHHHh..',
        '.hHJHHHHHHHHHHh.',
        '.hHHHHHHHHHHRYh.',
        '.hHHHhhhhhhhRrh.',
        '.hHHhSSSSSSSShh.',
        '.hHHhssEssssEh..',
        '.hHHhSSESSSSEs..',
        '.hHHhSSSSSsSSS..',
        '.hHHHsSSSSSSSs..',
        '.hHHHhsSSmmSs...',
        '.hHHHHhssssss...',
        '.hHHHh..........',
        '.hHHHh..........',
        '..hhh...........',
      ] },
    },
    bside: { base: 'back' },
  },
  ranger: {
    front: {
      head: { at: [14, 4], rows: [
        '.......aA.......',
        '......aAAa......',
        '.....aAQAAa.....',
        '....aAQAAAAa....',
        '...aAQAAAAAAa...',
        '..aAQAAAAAAAAa..',
        '..aAAhhhhhhAAa..',
        '..aAhsEssEshAa..',
        '..aAhSESSEShAa..',
        '..aAhSSssSShAa..',
        '..aAhsSSSSshAa..',
        '..aAAhsssshAAa..',
        '..aAAAhhhhAAAa..',
        '...aAAAAAAAAa...',
        '....aaaaaaaa....',
      ] },
      body: { at: [10, 19], rows: [
        '.........aAAAAa.........',
        '...aAQQAAAAAAAAAAQQAa...',
        '..aAQAAAAAAAAAAAAAAQAa..',
        '..aAAAAaTTTTTTTTaAAAAa..',
        '..aAAAaoTTTGTTTToaAAAa..',
        '..aAAAaoTTTTTTTToaAAAa..',
        '..aaaaaoTTTTTTTToaaaaa..',
        '..ttTt.oTTTTTTTTo.tTtt..',
        '..tTTt.oLLLGLLLLo.tTTt..',
        '..tTTt.oTTTTTTTTo.tTTt..',
        '..sSSs.oTTTTTTTTo.sSSs..',
        '..sSSs..TtTTTTtT..sSSs..',
        '........tTTTTTTt........',
        '........tttttttt........',
        '......PPPPPPPPPPPp......',
      ] },
      weapon: { at: [8, 16], rows: [
        '.d....', 'Wdd...', 'W.dD..', 'W..dD.', 'W..dD.', 'W...dD', 'W...dD', 'W...dD',
        'W...dD', 'W...dD', 'W...dD', 'W...LL', 'W...LL', 'W...LL', 'W...dD', 'W...dD',
        'W...dD', 'W...dD', 'W...dD', 'W...dD', 'W..dD.', 'W..dD.', 'W.dD..', 'Wdd...', '.d....',
      ] },
      atk: { at: [30, 17], rows: [
        '.......d......', '......Wdd.....', '......W.dD....', '.....W...dD...', '.....W...dD...',
        '....W.....dD..', '....W.....dD..', '...W......dD..', '...W......dD..', '..W.......dD..',
        '..W.......LL..', '.W........LL..', 'sSDDDDDDDDLLMM', '.W........LL..', '..W.......LL..',
        '..W.......dD..', '...W......dD..', '...W......dD..', '....W.....dD..', '....W.....dD..',
        '.....W...dD...', '.....W...dD...', '......W.dD....', '......Wdd.....', '.......d......',
      ] },
    },
    back: {
      head: { at: [14, 4], rows: [
        '.......aA.......',
        '......aAAa......',
        '.....aAQAAa.....',
        '....aAQAAAAa....',
        '...aAQAAAAAAa...',
        '..aAQAAAAAAAAa..',
        '..aAQAAAAAAAAa..',
        '..aAAAAAAAAAAa..',
        '..aAAAAAAAAAAa..',
        '..aAAAAAAAAAAa..',
        '..aAAAAAAAAAAa..',
        '..aaAAAAAAAAaa..',
        '..aaaAAAAAAaaa..',
        '...aAAAAAAAAa...',
        '....aaaaaaaa....',
      ] },
      behind: { at: [24, 12], rows: [
        'R.R.R..',
        'WRWRWR.',
        '.dDdDd.',
        '..tTTt.',
        '..tTTt.',
        '..tTTt.',
        '..tTTt.',
        '..tTTt.',
      ] },
      body: { at: [10, 19], rows: [
        '.........aAAAAa.........',
        '...aAQQAAAAAAAAAAQQAa...',
        '..aAQAAAAAAAAAAAAAAQAa..',
        '..aAAAAAAAAAAAAAAAAAAa..',
        '..aAAAAAAAAAAAAAAAAAAa..',
        '..aAAAAAAAAAAAAAAAAAAa..',
        '..aaaaaAAAAAAAAAAaaaaa..',
        '..ttTt.aAAAAAAAAa.tTtt..',
        '..tTTt.aAAAAAAAAa.tTTt..',
        '..tTTt.aAAAAAAAAa.tTTt..',
        '..sSSs.aAAAAAAAAa.sSSs..',
        '..sSSs.aAAAAAAAAa.sSSs..',
        '.......aAAAAAAAAa.......',
        '.......aAaAAAaAAa.......',
        '......aAAaAAAaAAAa......',
        '......aaa.aaa.aaaa......',
      ] },
      weapon: { at: [30, 16], rows: [
        '....d.', '...ddW', '..Dd.W', '.Dd..W', '.Dd..W', 'Dd...W', 'Dd...W', 'Dd...W',
        'Dd...W', 'Dd...W', 'Dd...W', 'LL...W', 'LL...W', 'LL...W', 'Dd...W', 'Dd...W',
        'Dd...W', 'Dd...W', 'Dd...W', 'Dd...W', '.Dd..W', '.Dd..W', '..Dd.W', '...ddW', '....d.',
      ] },
      atk: { at: [8, 17], rows: [
        '......d.......', '.....ddW......', '....Dd.W......', '...Dd...W.....', '...Dd...W.....',
        '..Dd.....W....', '..Dd.....W....', '..Dd......W...', '..Dd......W...', '..Dd.......W..',
        '..LL.......W..', '..LL........W.', 'MMLLDDDDDDDDSs', '..LL........W.', '..LL.......W..',
        '..Dd.......W..', '..Dd......W...', '..Dd......W...', '..Dd.....W....', '..Dd.....W....',
        '...Dd...W.....', '...Dd...W.....', '....Dd.W......', '.....ddW......', '......d.......',
      ] },
    },
    side: {
      head: { at: [14, 4], rows: [
        '...aA...........',
        '...aAAa.........',
        '...aAQAAa.......',
        '..aAQAAAAAa.....',
        '..aAQAAAAAAAa...',
        '.aAQAAAAAAAAAa..',
        '.aAAAAAAAhhhAa..',
        '.aAAAAAAhssEsa..',
        '.aAAAAAAhSSES...',
        '.aAAAAAAhSSSSs..',
        '.aAAAAAAAhSSS...',
        '.aAAAAAAAAhss...',
        '..aAAAAAAAAa....',
        '...aAAAAAAa.....',
        '....aaaaaa......',
      ] },
      body: { at: [10, 19], rows: [
        '.........aAAAa..........',
        '.....aAAAAAAAAAa........',
        '....aAQAAAAAAAAAa.......',
        '....aAAAAAAAAAaTa.......',
        '....aAAAAAaaaaaTa.......',
        '....aAAAAAattTatTa......',
        '....aAAAAAatTTatTa......',
        '....aAAAAAatTTatTa......',
        '....aAAAAAatTTaLLa......',
        '.....aAAAAatTTaTTa......',
        '.....aAAAAasSSsTTa......',
        '......aAAAasSSsTt.......',
        '......aAAAAaTTTTt.......',
        '.......aAAAattttt.......',
        '........aaaPPPPPp.......',
      ] },
      weapon: { at: [23, 16], rows: [
        '..d...', '..ddW.', '...dDW', '...dDW', '....dD', '....dD', '....dD', '....dD',
        '....dD', '....dD', '....dD', '....LL', '....LL', '....LL', '....dD', '....dD',
        '....dD', '....dD', '....dD', '....dD', '...dDW', '...dDW', '..ddW.', '..d...',
      ].map(r => r.slice(0, 6)) },
      atk: { at: [20, 17], rows: [
        '..............d.......', '.............Wdd......', '.............W.dD.....', '............W...dD....', '............W...dD....',
        '...........W.....dD...', '...........W.....dD...', '..........W......dD...', '..........W......dD...', '.........W.......dD...',
        'AAAAAAAAAW.......LL...', 'aaaaaaaaW........LL...', 'tTTTTTTsSDDDDDDDDLLMMM', 'ttttttttW........LL...', '.........W.......LL...',
        '..........W......dD...', '..........W......dD...', '...........W.....dD...', '...........W.....dD...', '............W...dD....',
        '............W...dD....', '.............W.dD.....', '.............Wdd......', '..............d.......',
      ] },
    },
    fside: { base: 'front',
      head: { at: [14, 4], rows: [
        '.......aA.......',
        '......aAAa......',
        '.....aAQAAa.....',
        '....aAQAAAAa....',
        '...aAQAAAAAAa...',
        '..aAQAAAAAAAAa..',
        '..aAAAhhhhhhAa..',
        '..aAAhssEsssEa..',
        '..aAAhSSESSSEa..',
        '..aAAhSSSSsSSa..',
        '..aAAhsSSSSSsa..',
        '..aAAAhssssshA..',
        '..aAAAAhhhhAAa..',
        '...aAAAAAAAAa...',
        '....aaaaaaaa....',
      ] },
    },
    bside: { base: 'back' },
  },
  raider_brawler: {
    front: {
      head: { at: [15, 4], rows: [
        '......Rr......',
        '......RRr.....',
        '.....rRRr.....',
        '...sSSRRSSs...',
        '..sSSSRRSSSs..',
        '.sSSSSSSSSSSs.',
        '.sSoooSSoooSs.',
        '.sSsEsSSsEsSs.',
        '.sSSSSssSSSSs.',
        '.sRRRRRRRRRRs.',
        '.sRRrRRRRrRRs.',
        '..RRRRRRRRRR..',
        '...rRRRRRRr...',
        '....rrrrrr....',
      ] },
      body: { at: [10, 19], rows: [
        '.........sSSSSs.........',
        '..MMMMsVVVSSSSVVVsSSSs..',
        '.MMMMMMVVVSSSSVVVSSSSSs.',
        '.oMoMoMVVVsSSsVVVSSSSSs.',
        '.sSSSSsVVVSSSSVVVsSSSSs.',
        '.sSSSSsVVVsSSsVVVsSSSSs.',
        '.sSSSsoVVVSSSSVVVosSSSs.',
        '.sSSSsoVVVsSSsVVVosSSSs.',
        '..sSSsoVVVVVVVVVVosSSs..',
        '..sSSsoLLLLGGLLLLosSSs..',
        '..sSSs.PPPPPPPPPP.sSSs..',
        '..oSSo.PPPPPPPPPP.oSSo..',
        '..sSSs.PPPPpPPPPP.sSSs..',
        '...ss..PPPPpPPPPP..ss...',
        '.......PPPPpPPPPP.......',
      ] },
      weapon: { at: [28, 31], rows: [
        '..DD..', '..Dd..', '.DDdd.', 'MDDDdM', '.DDDd.', 'MDDDdM', '.DDdd.', '..Md..',
      ] },
    },
    back: {
      head: { at: [15, 4], rows: [
        '......Rr......',
        '......RRr.....',
        '.....rRRr.....',
        '...sSSRRSSs...',
        '..sSSSRRSSSs..',
        '.sSSSSRRSSSSs.',
        '.sSSSSRRSSSSs.',
        '.sSSSSrRSSSSs.',
        '.sSSSSSSSSSSs.',
        '.sRRRRRRRRRRs.',
        '.sRRRRrRRRRRs.',
        '..RRRRrrRRRR..',
        '...ss.Rr.ss...',
        '....ssRrss....',
      ] },
      body: { at: [10, 19], rows: [
        '.........sSSSSs.........',
        '..sSSSsVVVVVVVVVVsMMMM..',
        '.sSSSSSVVVVVVVVVVMMMMMM.',
        '.sSSSSSVVVVVVVVVVMoMoMo.',
        '.sSSSSsVVVVVVVVVVsSSSSs.',
        '.sSSSSsVVVVvVVVVVsSSSSs.',
        '.sSSSsoVVVVvVVVVVosSSSs.',
        '.sSSSsoVVVVvVVVVVosSSSs.',
        '..sSSsoVVVVvVVVVVosSSs..',
        '..sSSsoLLLLLLLLLLosSSs..',
        '..sSSs.PPPPPPPPPP.sSSs..',
        '..oSSo.PPPPPPPPPP.oSSo..',
        '..sSSs.PPPPpPPPPP.sSSs..',
        '...ss..PPPPpPPPPP..ss...',
        '.......PPPPpPPPPP.......',
      ] },
      weapon: { at: [28, 31], rows: [
        '..DD..', '..Dd..', '.DDdd.', 'MDDDdM', '.DDDd.', 'MDDDdM', '.DDdd.', '..Md..',
      ] },
    },
    side: {
      head: { at: [15, 4], rows: [
        '....Rr........',
        '...RRRr.......',
        '..rRRRRr......',
        '..RRsSSSSs....',
        '.RRsSSSSSSs...',
        '.RsSSSSSSSSs..',
        '.sSSSSSSoooo..',
        '.sSSSSSSSsEs..',
        '.sSSSSSSSSSSs.',
        '.sSSSSSRRRRRR.',
        '.RRRRRRRRRrRR.',
        '..rRRRRRRRRR..',
        '...rRRRRRRr...',
        '....rrrrrr....',
      ] },
      body: { at: [10, 19], rows: [
        '..........sSSSs.........',
        '.......vVVVVVVVVs.......',
        '......vVVVVVVVVVSs......',
        '......vVVsSSSsVVSs......',
        '......vVsSSSSSsVSs......',
        '......vVsSSSSSsVSs......',
        '......vVsSSSSSsVSs......',
        '......vVsSSSSSsVSs......',
        '......vVVsSSSsVVVs......',
        '......LLLoSSSoLLLL......',
        '.......PPoSSSoPPPP......',
        '.......PPPSSSPPPPP......',
        '.......PPPPPPPPPPP......',
        '.......PPPPPPPPPPP......',
        '.......PPPPPPPPPPP......',
      ] },
      weapon: { at: [20, 30], rows: [
        '..DD..', '..Dd..', '.DDdd.', 'MDDDdM', '.DDDd.', 'MDDDdM', '.DDdd.', '..Md..',
      ] },
    },
    fside: { base: 'front' },
    bside: { base: 'back' },
  },
  raider_shooter: {
    front: {
      head: { at: [15, 6], rows: [
        '....hHHHHh....',
        '...hHJJHHHh...',
        '..hHJHHHHHHh..',
        '.hHJHHHHHHHHh.',
        '.hHHHHHHHHHHh.',
        '.hHHhSSSShHHh.',
        '.hHhKBKKBKhHh.',
        '.hHhKbKKbKhHh.',
        '.hHhsSSSSshHh.',
        '.hHXXXXXXXXHh.',
        '.hHXxXXXXxXHh.',
        '..hXXXXXXXXh..',
        '...xxxxxxxx...',
      ] },
      body: { at: [10, 19], rows: [
        '.........XXXXXX.........',
        '...cCCCCXXXXXXXXCCCCc...',
        '..cCYCCCCCxXXCCCCCCYCc..',
        '..cCYCCCCCCCCCCCCCCYCc..',
        '..cCCCcCCCCCCCCCCcCCCc..',
        '..cCCCcCCCLLCCCCCcCCCc..',
        '..cCCCcCCCCLLCCCCcCCCc..',
        '..cCCCcCCCCCLLCCCcCCCc..',
        '..cCCCcCCCCCCLLCCcCCCc..',
        '..cCCCcLLLLLLLLLLcCCCc..',
        '..cCCCcCCPPPPPPCCcCCCc..',
        '..sSSs.CCPPPPPPCC.sSSs..',
        '..sSSs.CCPPPPPPCC.sSSs..',
        '.......CCPPPPPPCC.......',
        '.......cCCPPPPCCc.......',
        '.......cCC....CCc.......',
        '.......cCc....cCc.......',
        '.......ccc....ccc.......',
      ] },
      weapon: { at: [30, 16], rows: [
        '..N.', '..NM', '..NM', '..NM', '..NM', '..NM', '..NM', '..NM', '..NM', '..NM', '..NM',
        '..NM', '.DNM', 'DDDN', 'DDDD', 'DDD.', '.DD.',
      ] },
    },
    back: {
      head: { at: [15, 6], rows: [
        '....hHHHHh....',
        '...hHJJHHHh...',
        '..hHJHHHHHHh..',
        '.hHJHHHHHHHHh.',
        '.hHHHHHHHHHHh.',
        '.hHHHHHHHHHHh.',
        '.hKKKKKKKKKKh.',
        '.hHHHHHHHHHHh.',
        '.hHHHHHHHHHHh.',
        '.hHHHHHHHHHHh.',
        '.hXXXXXXXXXXh.',
        '..hXXxxXXXXh..',
        '...xx..xxxx...',
      ] },
      body: { at: [10, 19], rows: [
        '.........XXXXXX.........',
        '...cCCCCCCCCCCCCCCCCc...',
        '..cCYCCCCCCCCCCCCCCYCc..',
        '..cCYCCCCCCCCCCCCCCYCc..',
        '..cCCCcCCCCCCCCCCcCCCc..',
        '..cCCCcCCCCCCCCCCcCCCc..',
        '..cCCCcCCCCCCCCCCcCCCc..',
        '..cCCCcCCCCCCCCCCcCCCc..',
        '..cCCCcCCCCCCCCCCcCCCc..',
        '..cCCCcLLLLLLLLLLcCCCc..',
        '..cCCCcCCCCcCCCCCcCCCc..',
        '..sSSs.CCCCcCCCCC.sSSs..',
        '..sSSs.CCCCcCCCCC.sSSs..',
        '.......CCCCcCCCCC.......',
        '.......cCCCcCCCCc.......',
        '.......cCCC..CCCc.......',
        '.......cCCc..cCCc.......',
        '.......ccc....ccc.......',
      ] },
      weapon: { at: [30, 16], rows: [
        '..N.', '..NM', '..NM', '..NM', '..NM', '..NM', '..NM', '..NM', '..NM', '..NM', '..NM',
        '..NM', '.DNM', 'DDDN', 'DDDD', 'DDD.', '.DD.',
      ] },
    },
    side: {
      head: { at: [15, 6], rows: [
        '....hHHHh.....',
        '...hHJJHHh....',
        '..hHJHHHHHh...',
        '.hHJHHHHHHHh..',
        '.hHHHHHHHHHh..',
        '.hHHHHHHhSSh..',
        '.hHHHHHHKKBK..',
        '.hHHHHHHKKbK..',
        '.hHHHHHHhSSSs.',
        '.hHHHHHXXXXXX.',
        '.hHHHHXXXXxXX.',
        '..hHHXXXXXXX..',
        '...xxxxxxxx...',
      ] },
      body: { at: [10, 19], rows: [
        '..........XXXX..........',
        '........cCCCCCCXc.......',
        '.......cCCYYCCCCCc......',
        '.......cCYYYYCCCCc......',
        '.......cCYCCCCCCCc......',
        '.......cCCcccccCCc......',
        '.......cCcCCCCcLCc......',
        '.......cCcCCCCcCLc......',
        '.......cCcCCCCcCCc......',
        '.......cLcCCCCcLLc......',
        '.......cCcsSSScPPc......',
        '.......cCcsSSScPPc......',
        '.......cCCccccCCCc......',
        '.......cCCCCCCCCCc......',
        '......cCCCCCCCCCCc......',
        '......cCCCCCCCCCc.......',
        '......ccCCCCCCCc........',
        '.......ccccccccc........',
      ] },
      weapon: { at: [18, 27], rows: [
        '..........NNNNNNNNNNMM',
        '..DDDDDDNNMMMMMMMMMMMN',
        '.DDDDDDDsSN...........',
        'DDDD.....N............',
        'DDD...................',
      ] },
    },
    fside: { base: 'front' },
    bside: { base: 'back' },
  },
  raider_heavy: {
    legs: HEAVY_LEGS,
    front: {
      head: { at: [14, 6], rows: [
        '....aAAAAAAa....',
        '..aAQQAAAAAAAa..',
        '.aAQQAAAAAAAAAa.',
        '.aAQAAAAAAAAAAa.',
        '.aAAArAAAAArAAa.',
        '.aAAAAAAAAAAAAa.',
        '.aooooooooooooa.',
        '.aoEEooooooEEoa.',
        '.aooooooooooooa.',
        '.aAAAAAAAAAAAAa.',
        '.aArAAAAAAAArAa.',
        '..aAAAAAAAAAAa..',
        '...aaaaaaaaaa...',
      ] },
      body: { at: [8, 19], rows: [
        '..........aAAAAAAa..........',
        '..aQQAAAAaAAAAAAAAaAAQQAAa..',
        '.aQQAAAAAaAQAAAAAAaAQQAAAAa.',
        '.aQAAAAAAaAAAAAAAAaAQAAAAAa.',
        '.aAAArAAAaAArrAAAAaAAArAAAa.',
        '..aaaaaaaoAAAAAAAAoaaaaaaa..',
        '..aAAAAAaoAAArAAAAoaAAAAAa..',
        '..aAAAAAaoAAAAAAAAoaAAAAAa..',
        '..aAAAAAaoAArAAAAAoaAAAAAa..',
        '..aAAAAAaoLLLGGLLLoaAAAAAa..',
        '..aQQQQQa.PPPPPPPP.aQQQQQa..',
        '..aAAAAAa.PPPPPPPP.aAAAAAa..',
        '..aAAAAAa.PPPPPPPP.aAAAAAa..',
        '...aaaaa.PPPPPPPPPP.aaaaa...',
        '........PPPPPPPPPPPP........',
      ] },
      weapon: { at: [27, 32], rows: [
        '....Dd....', '....Dd....', '....Dd....', '....Dd....', '....Dd....', '....Dd....',
        '....Dd....', '....Dd....', '....Dd....', '.NMMMMMMN.', 'NMMMMMMMMN', 'NMMMMMMMMN',
        'NNNNNNNNNN', '.NNNNNNNN.',
      ] },
    },
    back: {
      head: { at: [14, 6], rows: [
        '....aAAAAAAa....',
        '..aAQQAAAAAAAa..',
        '.aAQQAAAAAAAAAa.',
        '.aAQAAAAAAAAAAa.',
        '.aAAArAAAAArAAa.',
        '.aAAAAAAAAAAAAa.',
        '.aAAAAAAAAAAAAa.',
        '.aAAArAAAArAAAa.',
        '.aAAAAAAAAAAAAa.',
        '.aAAAAAAAAAAAAa.',
        '.aaAAAAAAAAAAaa.',
        '..aaaAAAAAAaaa..',
        '...aaaaaaaaaa...',
      ] },
      body: { at: [8, 19], rows: [
        '..........aAAAAAAa..........',
        '..aQQAAAAaAAAAAAAAaAAQQAAa..',
        '.aQQAAAAAaAQAAAAAAaAQQAAAAa.',
        '.aQAAAAAAaAAAAAAAAaAQAAAAAa.',
        '.aAAArAAAaAAAAAAAAaAAArAAAa.',
        '..aaaaaaaoAAAArrAAoaaaaaaa..',
        '..aAAAAAaoAAAArrAAoaAAAAAa..',
        '..aAAAAAaoAAAAAAAAoaAAAAAa..',
        '..aAAAAAaoAAAAAAAAoaAAAAAa..',
        '..aAAAAAaoLLLLLLLLoaAAAAAa..',
        '..aQQQQQa.PPPPPPPP.aQQQQQa..',
        '..aAAAAAa.PPPPPPPP.aAAAAAa..',
        '..aAAAAAa.PPPPPPPP.aAAAAAa..',
        '...aaaaa.PPPPPPPPPP.aaaaa...',
        '........PPPPPPPPPPPP........',
      ] },
      weapon: { at: [27, 32], rows: [
        '....Dd....', '....Dd....', '....Dd....', '....Dd....', '....Dd....', '....Dd....',
        '....Dd....', '....Dd....', '....Dd....', '.NMMMMMMN.', 'NMMMMMMMMN', 'NMMMMMMMMN',
        'NNNNNNNNNN', '.NNNNNNNN.',
      ] },
    },
    side: {
      head: { at: [14, 6], rows: [
        '....aAAAAAa.....',
        '..aAQQAAAAAAa...',
        '.aAQQAAAAAAAAa..',
        '.aAQAAAAAAAAAa..',
        '.aAAArAAAAAAAa..',
        '.aAAAAAAAAAAAa..',
        '.aAAAAAAAAoooo..',
        '.aAAAAAAAAoEEo..',
        '.aAAAAAAAAoooo..',
        '.aAAAAAAAAAAAa..',
        '.aAAArAAAAAAAa..',
        '..aAAAAAAAAAa...',
        '...aaaaaaaaa....',
      ] },
      body: { at: [8, 19], rows: [
        '...........aAAAAAa..........',
        '.........aAAAAAAAAAa........',
        '........aAAAAQQQAAAAa.......',
        '.......aAAAAQQQQQAAAAa......',
        '.......aAAAAQAAAAAAAAa......',
        '.......aAAAAArAAAAAAAa......',
        '.......aAAaaaaaaaaAAAa......',
        '.......aAAaAAAAAAaAAAa......',
        '.......aAAaAAAAAAaAAAa......',
        '.......aLLaAAAAAAaLLLa......',
        '.......aPPaQQQQQQaPPPa......',
        '.......aPPaAAAAAAaPPPa......',
        '.......aPPaAAAAAAaPPPa......',
        '........PPPaaaaaaPPP........',
        '........PPPPPPPPPPPP........',
      ] },
      weapon: { at: [17, 32], rows: [
        '....Dd....', '....Dd....', '....Dd....', '....Dd....', '....Dd....', '....Dd....',
        '....Dd....', '....Dd....', '....Dd....', '.NMMMMMMN.', 'NMMMMMMMMN', 'NMMMMMMMMN',
        'NNNNNNNNNN', '.NNNNNNNN.',
      ] },
    },
    fside: { base: 'front' },
    bside: { base: 'back' },
  },
};

// Frame list per actor, matching the keys buildAtlases packs:
// <id><dir>, <id><dir>_step, <id><dir>_step2, <id>_atk<dir>. Side is the bare key.
// Back views paint the weapon before the body so it reads as held in front of him.
const ART_DIRS = { '': 'side', '_front': 'front', '_back': 'back', '_fside': 'fside', '_bside': 'bside' };

function _artParts(art, dir) {
  const d = art[dir];
  return d.base ? Object.assign({}, art[d.base], d, { back: art[d.base].back || d.base === 'back' }) : Object.assign({}, d, { back: dir === 'back' });
}

function _artLayers(parts, legs, atk) {
  const weapon = atk ? (parts.atk || parts.weapon) : parts.weapon;
  return parts.back
    ? [legs, weapon, parts.behind, parts.body, parts.over, parts.head]
    : [legs, parts.behind, parts.body, parts.over, weapon, parts.head];
}

function pixelActorFrames(id) {
  const art = SPRITE_ART[id], pal = PLAYER_PAL[id], out = {};
  for (const [sfx, dir] of Object.entries(ART_DIRS)) {
    const parts = _artParts(art, dir);
    const kind = dir === 'side' ? 'side' : 'front';
    const L = (rows, flip) => ({ at: [22 - rows[0].length / 2, 34], rows, flip });
    const legs = art.legs || LEGS;
    out[id + sfx] = paintGrid(_artLayers(parts, L(legs[kind])), pal);
    out[id + sfx + '_step'] = paintGrid(_artLayers(parts, L(legs[kind + '_step'])), pal);
    out[id + sfx + '_step2'] = paintGrid(_artLayers(parts, L(legs[kind + '_step'], true)), pal);
    if (art.front.atk) out[id + '_atk' + sfx] = paintGrid(_artLayers(parts, L(legs[kind]), true), pal);
  }
  return out;
}

// Called from buildTextures before polishActors/buildAtlases, which add the outline and
// foot shadow and pack these into player_atlas / raider_atlas.
function buildPixelActors(scene) {
  for (const id of Object.keys(SPRITE_ART)) {
    for (const [key, canvas] of Object.entries(pixelActorFrames(id))) scene.textures.addCanvas(key, canvas);
  }
}
